import { dir } from "i18next"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "../globals.css"

import { languages } from "../i18n/settings"

const inter = Inter({ subsets: ["latin"] })

export async function generateStaticParams() {
  return languages.map((lang) => ({ lang }))
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
  params: { lang },
}: Readonly<{
  children: React.ReactNode
  params: { lang: string }
}>) {
  return (
    <html lang={lang} dir={dir(lang)}>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
